### ISSUE TITLE
Please put tutorial/link for the official replacement

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [krossovochkin/Android-SwipeToDismiss-RecyclerView#10]
You wrote that this library is deprecated as there is an official way to do it.
please show how, or put a link...

**Comment by krossovochkin** [comment]
Hi

You can find some kind of example [here](http://stackoverflow.com/a/30601554/1533933).

**Comment by AndroidDeveloperLB** [comment]
Thank you. I've also noticed you've put a link on the main page
